export const SPEND_CATEGORIES = [
  'Artykuły spożywcze',
  'Paliwo',
  'Transport',
  'Uroda, fryzjer',
  'Kosmetyki',
  'Zakupy przez internet',
  'Restauracje',
  'Kino',
  'Kluby',
  'Sport',
  'Książki',
  'Podróże',
  'Subskrypcje',
  'Akcesoria domowe',
  'Inne',
  'Podatki',
  'Internet, TV, telefon',
  'Transport publiczny',
  'Dom',
  'Wyposażenie domu',
  'Ubrania',
  'Rachunki',
];
